# Generated by Django 4.0.1 on 2022-01-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_uni', models.CharField(max_length=250)),
                ('title', models.TextField()),
                ('overview', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.TextField()),
                ('eob', models.TextField()),
                ('country', models.TextField()),
                ('type', models.TextField()),
                ('group_size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField()),
                ('event', models.TextField()),
                ('phone_number', models.TextField()),
                ('email_address', models.TextField()),
                ('booking_package', models.TextField()),
                ('payment', models.TextField()),
                ('sits', models.TextField()),
                ('special_request', models.TextField()),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('city', models.TextField()),
                ('loc', models.TextField()),
            ],
        ),
    ]
