# Generated by Django 3.2.10 on 2022-02-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220211_0501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='tours',
        ),
    ]
