# Generated by Django 3.2.10 on 2022-02-11 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_event_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='views',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
