# Generated by Django 3.2.10 on 2022-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_eventpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('cost', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EventPackage',
        ),
    ]
