# Generated by Django 3.2.10 on 2022-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220211_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('description', models.TextField()),
                ('cost', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='event_packages',
        ),
    ]
