# Generated by Django 3.2.10 on 2022-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tourschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('media_type', models.TextField()),
                ('media_name', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('owner', models.TextField()),
                ('date_added', models.DateField()),
            ],
        ),
    ]
