# Generated by Django 3.2.10 on 2022-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('owner', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
