# Generated by Django 3.2.10 on 2022-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('fb', models.TextField()),
                ('twi', models.TextField()),
                ('linked', models.TextField()),
                ('img', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('owner', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='url_parse',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='tours',
            name='url_parse',
            field=models.TextField(default='none'),
        ),
    ]
